VERTICAL:
  COBBLESTONE:
    name: "&eCobblestone Genbucket"
    lore:
    - "a"
    - "b"
    - "c"
    slot: 29
    costOfPurchase: 20
    costOfPlacement: 30
  OBSIDIAN:
    name: "&eObsidian Genbucket"
    lore:
    - "d"
    - "e"
    - "f"
    slot: 30
    costOfPurchase: 10
    costOfPlacement: 100