VERTICAL:
  COBBLESTONE:
    name: "&eCobblestone Genbucket"
    lore:
    - "&c$30 per use"
    slot: 29
    costOfPurchase: 20
    costOfPlacement: 30
  OBSIDIAN:
    name: "&eObsidian Genbucket"
    lore:
    - "&c$100 per use"
    slot: 30
    costOfPurchase: 10
    costOfPlacement: 100